### ISSUE TITLE
Order 23 results

### ISSUE THREAD

**Issue by curtisbright** [BrianLi009/PhysicsCheck_log#1]
The results from the order 23 search should be archived.

**Comment by BrianLi009** [comment]
I tried zipping it:
remote: error: File order-23/all-cubes.zip is 219.91 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File order-23/all-exhaust.zip is 142.30 MB; this exceeds GitHub's file size limit of 100.00 MB

I can probably separate the logs into 3 folders, zip them and then push it.
